DROP TABLE public.version_control;
CREATE TABLE public.version_control (
    migration_id SERIAL,  
    archived_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    subject_id INTEGER,
    adrc_long_id INTEGER,
    ad_disease_modifying VARCHAR(255),
    ad_symptomatic VARCHAR(255),
    demographic_language_caregiver VARCHAR(255),
    demographic_language_testing VARCHAR(255),
    demographic_marital_status_combo VARCHAR(255),
    demographic_sex_at_birth VARCHAR(255),
    dob DATE,
    education_highest VARCHAR(255),
    demographic_race VARCHAR(255)[],
    ms_cancer VARCHAR(255),
    ms_diabetes_insulindep VARCHAR(255),
    ms_headtraum_wloss VARCHAR(255),
    ms_psychiatric_dx VARCHAR(255),
    ms_stroke VARCHAR(255),
    subject_occupation VARCHAR(255),
    veteran VARCHAR(255),
    demographic_gender VARCHAR(255),
    education_level INTEGER,
    mmse INTEGER,
    lst_drs INTEGER,
    lst_moca VARCHAR(255),
    cdrglob double precision,
	screen_contact_memory_prob VARCHAR(255),
    contact_memory_prob VARCHAR(255),
    referral_source_combo VARCHAR(255),
    referral_comments TEXT, 
    relationship_with_subject VARCHAR(255),
    contact_memory_prob_onset_yr DATE,
    yr_in_study INTEGER,
    visits_mmse INTEGER, 
    visits_mmse_date DATE, 
    visits_moca INTEGER, 
    visits_moca_date DATE, 
    visits_drs INTEGER, 
    visits_drs_date DATE,
    naccid VARCHAR(15),
    subject_status_adrc_xfer_name VARCHAR(255),
    subject_status_adrc_xfer VARCHAR(255),
    demographic_language_1 VARCHAR(255),
    demographic_language_1_degree VARCHAR(255),
    demographic_language_2 VARCHAR(255),
    demographic_language_2_degree VARCHAR(255),
    demographic_language_3 VARCHAR(255),
    demographic_language_3_degree VARCHAR(255),
    moca_mis INTEGER
);
