# define combo tables to replace SDSC data
MARITAL_STATUS_MAP = {
    1: "Married",
    2: "Widowed",
    3: "Divorced",
    4: "Separated",
    5: "Never married",
    6: "Living as married",
    8: "Other",
    9: "Unknown"
}

BIRTHSEX_MAP = {
    1: "Male",
    2: "Female",
    8: "Prefer not to answer",
    9: "Don't know"
}

LVLEDUC_MAP = {
    1: "Less than high school",
    2: "High school or GED",
    3: "Some college",
    4: "Bachelor's degree",
    5: "Master's degree",
    6: "Doctorate",
    9: "Don't know"
}

VETERAN_MAP = {
    1: "Yes",
    2: "No",
    9: "Unknown"
}

MEMWORS_MAP = {
    0: "No",
    1: "Yes, but this does not worry me",
    2: "Yes, and this worries me",
    9: "Don't know / Prefer not to answer"
}

REFERSC_MAP = {
    1: "Self-referral",
    2: "Non-professional contact (spouse/partner, relative, friend, coworker, etc.)",
    3: "ADC participant referral",
    4: "ADC clinician, staff, or investigator referral",
    5: "Nurse, doctor, or other health care provider",
    6: "Other research study clinician/staff/investigator (non-ADC, e.g., ADNI, Women’s Health Initiative)",
    8: "Other",
    9: "Unknown", 
    90: "Promotora"
}

LANG_MAP = {
    1: "English",
    2: "Spanish",
    3: "Other"
}

INRELTO_MAP = {
    1: "Spouse/partner",
    2: "Child",
    3: "Sibling",
    4: "Other relative",
    5: "Friend/neighbor",
    6: "Paid caregiver/provider",
    7: "Other (specify)"
}

YES_NO_MAP = {
    0: "No",
    1: "Yes",
    9: "Unknown"
}

CANCER_DIABETES_STATUS_MAP = {
    0: "Absent",
    1: "Recent/active",
    2: "Remote/inactive",
    9: "Unknown"
}

LANGUAGE_PROFICIENCY_MAP = {
    0: "Unknown",
    1: "Almost None",
    2: "Very Poor",
    3: "Fair",
    4: "Functional",
    5: "Good",
    6: "Very Good",
    7: "Like Native"
}

RACE_MAP = {
    1: "White",
    2: "Black",
    3: "American Indian or Alaska Native", 
    4: "Native Hawaiian or Other Pacific Islander",
    5: "Asian",
    50: "Other",
    88: "None Reported",
    99: "Unknown"
}

GENDER_MAP = {
    1: "Man",   
    2: "Woman",
    3: "Transgender man",
    4: "Transgender woman",
    5: "Non-binary/genderqueer",
    6: "Two-Spirit",
    7: "I use a different term",
    8: "Don't know",
    9: "Prefer not to answer"
}

OCCUPATION_MAP = {
    101: "Actuaries",
    102: "Architects",
    103: "Bank officers",
    104: "Certified public accountants",
    105: "Chief executives (CEO, CFO, COO)",
    106: "Clergy (professionally trained)",
    107: "Commissioned officers in the military",
    108: "Dentists",
    109: "Economists",
    110: "Engineers (Masters level and above)",
    111: "Financial managers",
    112: "Federal government officials",
    113: "Large business owners",
    114: "Lawyers / judges",
    115: "Mathematicians",
    116: "Major contractors",
    117: "Orthodontists",
    118: "Physicians",
    119: "Professor / University teachers",
    120: "Psychologists",
    121: "Research scientists",
    122: "Urban and regional planners",
    123: "Veterinarians",
    124: "VP of large business",

    201: "Accountants",
    202: "Advertising executives",
    203: "Authors",
    204: "Branch managers",
    205: "Building contractors",
    206: "Business managers",
    207: "Chiropractors",
    208: "Computer programmer",
    209: "Computer specialists",
    210: "Database developer",
    211: "Editors",
    212: "Engineers (no advanced degree)",
    213: "Executive managers",
    214: "Industrial farm owners",
    215: "Furniture business owners",
    216: "Jewelers",
    217: "Labor relations consultants",
    218: "Librarians",
    219: "Manufacturing owners",
    220: "Medium business owners",
    221: "Musicians / composers",
    222: "Nurses",
    223: "Office managers",
    224: "Opticians",
    225: "Personnel managers",
    226: "Pharmacists",
    227: "Pilots",
    228: "Police chief / sheriff",
    229: "Postmaster",
    230: "Production managers (TV / radio)",
    231: "Public administration officials",
    232: "Public health officers",
    233: "Purchasing managers",
    234: "Real estate brokers",
    235: "Research assistants",
    236: "Sales engineers",
    237: "Sales managers",
    238: "Social workers",
    239: "State / Local government officials",
    240: "Teachers (Elementary & high school)",

    301: "Actors",
    302: "Administrative assistants",
    303: "Advertising agents",
    304: "Artists",
    305: "Bakers",
    306: "Beauty shop owners",
    307: "Chefs",
    308: "Chief clerks",
    309: "Clergy (not professionally trained)",
    310: "Court reporters",
    311: "Credit managers",
    312: "Dental hygienists",
    313: "Department store managers",
    314: "Deputy sheriffs",
    315: "Dietitians / Nutritionists",
    316: "Dispatchers",
    317: "Florists",
    318: "Funeral directors",
    319: "Insurance agents",
    320: "Laboratory assistants",
    321: "Landscape planners",
    322: "Noncommissioned officers in the military (at or above rank of master sergeant / C.P.O.)",
    323: "Morticians",
    324: "Newspaper / TV reporters",
    325: "Photographers",
    326: "Piano teachers",
    327: "Radio / TV announcers",
    328: "Real estate agents",
    329: "Restaurant owners",
    330: "Sales representatives",
    331: "Service managers",
    332: "Small business owners",
    333: "Store managers",
    334: "Surveyors",
    335: "Title searchers",
    336: "Tool designers",
    337: "Traffic managers",
    338: "Travel agents",
    339: "Yard masters (railroad)",

    401: "Bank tellers",
    402: "Bill collectors",
    403: "Bookkeepers",
    404: "Claims examiners",
    405: "Drafters",
    406: "Driving teachers",
    407: "Factory supervisors",
    408: "Small farm owners / farmers",
    409: "Flower shop workers",
    410: "Human resources workers",
    411: "Laboratory technicians",
    412: "Newsstand operators",
    413: "Post office clerks",
    414: "Railroad conductors",
    415: "Railroad train engineers",
    416: "Receptionists",
    417: "Route managers",
    418: "Sales clerks",
    419: "Secretaries / stenographers",
    420: "Shipping clerks",
    421: "Tailors",
    422: "Tax clerks",
    423: "Telephone company workers",
    424: "Telephone operators",
    425: "Timekeepers",
    426: "Toll collectors",
    427: "Tower operators",
    428: "Truck dispatchers",
    429: "Typists",
    430: "Utility workers",
    431: "Warehouse clerks",
    432: "Window store trimmers",

    501: "Auto body repairers",
    502: "Barbers",
    503: "Boiler repairers",
    504: "Bookbinders",
    505: "Brewers",
    506: "Cabinet makers",
    507: "Carpenters",
    508: "Cement layers / finishers",
    509: "Checkers / examiners / inspectors",
    510: "Cheese makers",
    511: "Construction forepeople",
    512: "Die makers",
    513: "Electricians",
    514: "Engravers",
    515: "Exterminators",
    516: "Firefighters",
    517: "Gardeners / landscapers",
    518: "Glassblowers",
    519: "Glaziers",
    520: "Gun smiths",
    521: "Hair stylists",
    522: "Heavy equipment operators",
    523: "Home repairs",
    524: "Iron workers",
    525: "Kitchen workers / cooks",
    526: "Locksmiths",
    527: "Machinists",
    528: "Mail carriers",
    529: "Maintenance forepeople",
    530: "Masons",
    531: "Mechanics",
    532: "Millwrights",
    533: "Noncommissioned officers in the military (below rank of master sergeant / C.P.O.)",
    534: "Painters",
    535: "Paperhangers",
    536: "Patrolmen",
    537: "Piano builders",
    538: "Piano tuners",
    539: "Plumbers",
    540: "Police officers",
    541: "Postal workers",
    542: "Printers",
    543: "Radio / TV maintenance",
    544: "Railroad brake operators",
    545: "Repair people",
    546: "Seamstresses / seamsters",
    547: "Sheet metal workers",
    548: "Ship smiths",
    549: "Shoe repairers",
    550: "Steelworkers",
    551: "Tile layers",
    552: "Tool makers",
    553: "Upholsterers",
    554: "Utility line workers",
    555: "Weavers",
    556: "Welders",

    601: "Apprentices (electrician / printers / etc.)",
    602: "Assembly line workers",
    603: "Bartenders",
    604: "Building superintendents",
    605: "Bus drivers",
    606: "Cab / taxi drivers",
    607: "Cashiers",
    608: "Child care workers (not private household)",
    609: "Cooks (short order)",
    610: "Corrections workers",
    611: "Delivery people",
    612: "Dry cleaning pressers",
    613: "Elevator operators",
    614: "Enlisted military personnel (other than noncommissioned officers)",
    615: "Factory machine operators",
    616: "Factory workers",
    617: "Foundry workers",
    618: "Garage and gas station assistants",
    619: "Greenhouse workers",
    620: "Guards / security watch people",
    621: "Machine operators",
    622: "Meat cutters / packers",
    623: "Meter readers",
    624: "Nursing aides / attendants",
    625: "Oil delivery people",
    626: "Practical nurses",
    627: "Pump operators",
    628: "Receivers / checkers",
    629: "Servers (waiters / waitresses)",
    630: "Signal operators (railroad)",
    631: "Truck drivers",
    632: "Wood workers",
    633: "Wrappers (stores / factories)",

    701: "Amusement park workers",
    702: "Cafeteria workers",
    703: "Car cleaners",
    704: "Child care workers (private household)",
    705: "Construction laborers",
    706: "Dairy workers",
    707: "Deck hands",
    708: "Farm laborers",
    709: "Fishers",
    710: "Freight handlers",
    711: "Garbage collectors",
    712: "Grave diggers",
    713: "Homemakers",
    714: "House cleaners",
    715: "Janitors",
    716: "Junk / recycle sorters",
    717: "Laundry workers",
    718: "Messengers",
    719: "Peddlers",
    720: "Porters",
    721: "Roofing laborers",
    722: "Shoe shiners",
    723: "Stagehands",
    724: "Stock handlers",
    725: "Street cleaners",
    726: "Unemployed",
    727: "Unskilled factory workers",
    728: "Unspecified laborers",
    729: "Window cleaners",
    730: "Woodchoppers",
    731: "Worked while incarcerated",
}

STATUS_MAP = {
    1: "Annual in-person UDS follow-up",
    2: "Annual UDS follow-up by telephone", 
    3: "Minimal contact"
}